/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { FunctionModel } from "./FunctionModel";
import { FunctionModelCountArgs } from "./FunctionModelCountArgs";
import { FunctionModelFindManyArgs } from "./FunctionModelFindManyArgs";
import { FunctionModelFindUniqueArgs } from "./FunctionModelFindUniqueArgs";
import { DeleteFunctionModelArgs } from "./DeleteFunctionModelArgs";
import { FunctionModelService } from "../functionModel.service";
@graphql.Resolver(() => FunctionModel)
export class FunctionModelResolverBase {
  constructor(protected readonly service: FunctionModelService) {}

  async _functionModelsMeta(
    @graphql.Args() args: FunctionModelCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [FunctionModel])
  async functionModels(
    @graphql.Args() args: FunctionModelFindManyArgs
  ): Promise<FunctionModel[]> {
    return this.service.functionModels(args);
  }

  @graphql.Query(() => FunctionModel, { nullable: true })
  async functionModel(
    @graphql.Args() args: FunctionModelFindUniqueArgs
  ): Promise<FunctionModel | null> {
    const result = await this.service.functionModel(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => FunctionModel)
  async deleteFunctionModel(
    @graphql.Args() args: DeleteFunctionModelArgs
  ): Promise<FunctionModel | null> {
    try {
      return await this.service.deleteFunctionModel(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
