/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Method } from "./Method";
import { MethodCountArgs } from "./MethodCountArgs";
import { MethodFindManyArgs } from "./MethodFindManyArgs";
import { MethodFindUniqueArgs } from "./MethodFindUniqueArgs";
import { DeleteMethodArgs } from "./DeleteMethodArgs";
import { MethodService } from "../method.service";
@graphql.Resolver(() => Method)
export class MethodResolverBase {
  constructor(protected readonly service: MethodService) {}

  async _methodsMeta(
    @graphql.Args() args: MethodCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Method])
  async methods(@graphql.Args() args: MethodFindManyArgs): Promise<Method[]> {
    return this.service.methods(args);
  }

  @graphql.Query(() => Method, { nullable: true })
  async method(
    @graphql.Args() args: MethodFindUniqueArgs
  ): Promise<Method | null> {
    const result = await this.service.method(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Method)
  async deleteMethod(
    @graphql.Args() args: DeleteMethodArgs
  ): Promise<Method | null> {
    try {
      return await this.service.deleteMethod(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
